# Generated by Django 3.0.2 on 2020-03-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='headline',
            new_name='short_txt',
        ),
    ]
