# Generated by Django 3.0.2 on 2020-04-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200425_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about_txt',
            field=models.TextField(default=''),
        ),
    ]
