# Generated by Django 3.0.2 on 2020-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('utxt', models.TextField(default='')),
                ('email', models.TextField(default='')),
            ],
        ),
    ]
